// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ARate: typeof import('ant-design-vue/es')['Rate']
  }
}

export { }
